Upgrade/kubernetes v1.22
porter-dev/porter-charts pull request #171
Opened 2021-12-25 20:31 UTC by nikokon

Was setting up dev environment in order to get cracking on implementing some features when I noticed I was having trouble deploying a new app with ingress in my local minikube cluster. 

Some of the beta-apis have been deprecated in kubernetes v1.22 and started following this "guide".

https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

I think there are some more charts that need updating. mongodb, porteragent, prometheus for example use the "authorization.k8s.io/v1beta1"

While this PR does not adress those, I wanted to submit it as I'm not that experienced in best practices etc when it comes to versioning and deprecations using helm.

When do we allow breaking changes? when do we stop supporting kubernetes EOL versions etc? 🤷

2021-12-25 20:37 UTC, nikokon commented on applications/web/templates/ingress.yaml
>  apiVersion: extensions/v1beta1
was this removed in v1.14? when should we remove this from the chart definition? :) 
I'm just keeping it as a defense mechanism but would love to learn of what our thoughts are regarding this.

2022-02-01 16:36 UTC, lenn4rd commented
Anything I can do to expedite this and finish up this pull request so it can be merged into Porter?

2022-02-08 15:35 UTC, nikokon commented on applications/web/templates/ingress.yaml
> +{{- $allHosts := concat .Values.ingress.hosts, .Values.ingress.porter_hosts -}}
Uncertain about the syntax (that's why I put the pr in dragit state). Will the comma be an issue?

2022-02-08 15:44 UTC, nikokon commented
> Anything I can do to expedite this and finish up this pull request so it can be merged into Porter?

I could have another look and just  clean it up a bit. 
@abelanger5 or anyone from porter have any input on this? With kubernetes release and deprecation schedule this issue must be quite pressing?

There are other templates in the repo that needs updating as I mentioned in my original comment

2022-02-09 01:45 UTC, abelanger5 commented
Hi @nikokon, thanks for this PR and apologies for the delay in response. 

Requested @rudimk to review this PR and test that it's backwards-compatible.

2022-02-09 10:10 UTC, nikokon commented
No worries! :)

2022-02-21 17:42 UTC, rudimk commented
Hey @nikokon - so very sorry I haven't been able to get around to reviewing this. I'll be sure to take care of it either today or early tomorrow. Thanks ever so much!

2022-03-17 14:25 UTC, nikokon commented
ping @rudimk :)

2022-03-22 08:36 UTC, rudimk commented
Hey @nikokon - sitting on this today, the aim is to spin up a couple of testbed clusters running K8s v1.22 and test your changes out.

2022-03-29 16:14 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +{{- $allHosts := concat .Values.ingress.hosts, .Values.ingress.porter_hosts -}}
```suggestion
{{- $allHosts := concat .Values.ingress.hosts .Values.ingress.porter_hosts -}}
```

Yes, this comma will cause issues - I've tested that removing it will resolve Helm parsing errors.

2022-03-29 16:15 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +  {{- if not .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
```suggestion
  {{- if not (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") }}
```

Nested parentheses required since `not` requires a single argument -- alternatively you can use piping via `.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" | not`

2022-03-29 16:17 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
```suggestion
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
```

We will need to replace all instances of `networking.k8s.io/v1` with `networking.k8s.io/v1/Ingress` as there are API versions of `networking.k8s.io/v1` that don't contain an `Ingress` resource. Adding the resource kind ensures that this resource kind exists. From [Helm docs](https://helm.sh/docs/chart_template_guide/builtin_objects/):

> Capabilities.APIVersions.Has $version indicates whether a version (e.g., batch/v1) or resource (e.g., apps/v1/Deployment) is available on the cluster.

2022-03-29 16:18 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
```suggestion
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
```

2022-03-29 16:18 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +                {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
```suggestion
                {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}                
```

2022-03-29 16:18 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
```suggestion
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
```

2022-03-29 18:56 UTC, nikokon commented
hey @abelanger5 I applied your suggestions from the code review. took a while before I realized I could do it in bulk 🥲 
First time I've come across that functionality, with code suggestions ready to be applied in the review process. Really nice!

Feel free to merge if all looks good!

2022-03-30 15:44 UTC, abelanger5 requested changes
Hey @nikokon, I've added a few more code review comments after testing on various clusters.

2022-03-30 15:44 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta" -}}
```suggestion
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
```

I believe this should be `v1beta1`?

2022-03-30 15:44 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +apiVersion: networking.k8s.io/v1beta
```suggestion
apiVersion: networking.k8s.io/v1beta1
```

2022-03-30 15:44 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
> +              pathType: Prefix
```suggestion
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              pathType: ImplementationSpecific
              {{- end }}
```

I believe that `ImplementationSpecific` matches the previous behavior more closely than `Prefix`, and we only want to add `pathType` if the user is on `networking.k8s.io/v1`. Though I'm not sure about `networking.k8s.io/v1beta1`.

2022-03-30 15:44 UTC, abelanger5 commented on applications/web/templates/ingress.yaml
>              - backend:
```suggestion
```

I think this lingering `backend:` block is throwing things off. Here's the block that worked for me:

```
            - {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              pathType: ImplementationSpecific
              {{- end }}
              backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
              {{- else }}
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
              {{- end }}
```

2022-03-30 15:49 UTC, abelanger5 commented
Additionally -- upgrades once a user is on `1.22` will throw the following error:

```
UPGRADE FAILED: current release manifest contains removed kubernetes api(s)
for this kubernetes version and it is therefore unable to build the kubernetes
objects for performing the diff
```

Even though GKE will support the deprecated `extensions/v1beta1` API until 1.23, this error will still be thrown when the user attempts to upgrade.  

According to the Helm docs (https://helm.sh/docs/topics/kubernetes_apis/#helm-users), we will need to patch an existing Helm release with the new API versions before the user can upgrade. As a result, we cannot merge this in until we're able to perform this patch from the Porter server. Hopefully this won't take too long to get added.

2022-03-31 13:55 UTC, nikokon commented
@abelanger5 
I've commited your suggestions.

2022-03-31 16:39 UTC, abelanger5 approved these changes

2022-03-31 16:39 UTC, merged